// All player-visible text. Switching language = swapping this data.
export const STR = {
  title: 'DEADZONE',
  subtitle: 'WASTELAND PVP',
  enterName: 'CALLSIGN',
  play: 'DROP IN',
  connecting: 'CONNECTING TO THE WASTELAND…',
  reconnecting: 'CONNECTION LOST — RECONNECTING…',
  roomFull: 'ROOM FULL — TRY ANOTHER LINK',
  invite: 'INVITE LINK',
  copied: 'COPIED',
  copy: 'COPY',
  waiting: 'ALONE IN THE WASTE — SEND THE INVITE LINK TO HUNT HUMANS',
  killTargetInfo: 'FIRST TO {n} KILLS TAKES THE MATCH',
  respawnIn: 'RESPAWN IN {n}',
  youDied: 'YOU DIED',
  killedBy: 'DROPPED BY {name}',
  matchOver: '{name} TAKES THE MATCH',
  newMatchIn: 'NEW MATCH IN {n}',
  reload: 'RELOAD [R]',
  scoreboardHint: 'HOLD TAB — SCOREBOARD',
  kills: 'K',
  deaths: 'D',
  hp: 'HP',
  feedKilled: '{a} ✕ {b}',
  joined: '{name} entered the deadzone',
  left: '{name} left',
  pickedShotgun: 'RIOT-12 SHOTGUN',
  pickedLongshot: 'LONGSHOT RIFLE',
  pickedHealth: '+50 HP',
  weaponNames: { rifle: 'SCAV RIFLE', shotgun: 'RIOT-12', longshot: 'LONGSHOT' },
  touchFire: 'FIRE',
  touchNade: 'NADE',
  touchAds: 'AIM',
  touchJump: 'JMP',
  touchReload: 'RLD',
  clickToAim: 'CLICK TO TAKE AIM',
  padNote: 'XBOX / PLAYSTATION CONTROLLER SUPPORTED — PLUG IN AND PRESS ANY BUTTON',
};
